### ISSUE TITLE
Table overflow variant

### ISSUE THREAD

**Issue by arosenblum** [USDA-FSA/pcp#49]
On the Daily Pricing phase, we have an ngDIalog window to display the grid of commodities-to-markets.  Each cell in the grid that has a value displays a spinbox input control.  When we have lots of columns on the page, the spinboxes shrink down and cut off the value they are trying to display.

![image](https://user-images.githubusercontent.com/10815406/32917854-1b35bd7a-cae6-11e7-9592-dd34e67dd71b.png)

Maybe we need scrollbars (when applicable), and a min-width on the spinboxes?

**Comment by francisrupert** [comment]
@arosenblum,

Yeah, I've been wondering when column amount would get unwieldy and warrant an overflow option. 

Can you think of other tables throughout the experience that might suddenly have way more columns than we thought?

**Comment by francisrupert** [comment]
Current thinking...

```scss
.pcp-overflow-table {

  overflow: auto;
  max-height: 62vh;
  margin-top: 1em;
  margin-bottom: 2em;
  border: 1px solid $table-border-color;
  border-top-width: 2px;

  > .pcp-table {
    border: 0;
    margin: 0;
  }

  @media screen and (min-height: 720px) {
    max-height: 65vh;
  }

  @media screen and (min-height: 875px) {
    max-height: 63vh;
  }

  @media screen and (min-height: 1024px) {
    max-height: 68vh;
  }

}
```
