### ISSUE TITLE
Spinbox min-width

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/pcp#69]
possibly with some variations.

impacts #49

**Comment by francisrupert** [comment]
Approximate idea:

```scss
.pcp-spinbox {

  min-width: 8.2rem;

  &--small {
    min-width: 7.2rem;
  }

  &--large {
    min-width: 10rem;
  }

}

```
